server:
  port: 8081

spring:
  application:
    name: producer
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    username: admin
    password: admin


# 打印日志。比如你的包名在: cn.zyfvir  下
logging:
  level:
    cn:
      zyfvir: debug