server:
  port: 8082


seata:
  enabled: true
  application-id: business-service
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    #enable-degrade: false
    #disable-global-transaction: false


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_seate_demo2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: "service2"


# 打印日志。比如你的包名在: cn.zyfvir  下
logging:
  level:
    cn:
      zyfvir: debug